## Match districts with close election

In [2]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     |████████████████████████████████| 249 kB 6.3 MB/s
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install xlrd

Requirement already satisfied: xlrd in /opt/conda/lib/python3.9/site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

## Join dataframe for each states to create pairs of winner and loser with education filters.

In [63]:
import pandas as pd
table1 = pd.read_excel('2013_win.xlsx',sheet_name='Uttar_Pradesh')
table2 = pd.read_excel('2013_lose.xlsx',sheet_name='Uttar_Pradesh')

In [64]:
table1

,State_Name,Assembly_No,Constituency_No,Year,month,DelimID,Poll_No,Position,educdum,Margin_Percentage,...,No_Terms,Turncoat,Incumbent,Recontest,MyNeta_education,TCPD_Prof_Main,TCPD_Prof_Main_Desc,TCPD_Prof_Second,TCPD_Prof_Second_Desc,Election_Type
0,Uttar_Pradesh,16,4,2012,3,4,0,1,0,8.39,...,1,0,0,0,12th Pass,Politics,Party Worker,Agriculture,NaN,State Assembly Election (AE)
1,Uttar_Pradesh,16,9,2012,3,4,0,1,0,0.15,...,1,0,0,1,12th Pass,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
2,Uttar_Pradesh,16,12,2012,3,4,0,1,0,7.37,...,1,0,0,0,12th Pass,Business,NaN,NaN,NaN,State Assembly Election (AE)
3,Uttar_Pradesh,16,13,2012,3,4,0,1,0,5.32,...,1,0,0,0,12th Pass,Other,NaN,NaN,NaN,State Assembly Election (AE)
4,Uttar_Pradesh,16,14,2012,3,4,0,1,0,8.86,...,3,0,0,1,12th Pass,Business,NaN,NaN,NaN,State Assembly Election (AE)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,Uttar_Pradesh,16,386,2012,3,4,0,1,0,6.86,...,2,0,1,1,10th Pass,Business,Rent,NaN,NaN,State Assembly Election (AE)
114,Uttar_Pradesh,16,392,2012,3,4,0,1,0,7.78,...,1,0,0,0,12th Pass,Salaried Work or Employed,Insurance Agent,NaN,NaN,State Assembly Election (AE)
115,Uttar_Pradesh,16,395,2012,3,4,0,1,0,5.55,...,1,0,0,0,10th Pass,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
116,Uttar_Pradesh,16,397,2012,3,4,0,1,0,4.61,...,1,0,0,0,12th Pass,Other,NaN,NaN,NaN,State Assembly Election (AE)
117,Uttar_Pradesh,16,400,2012,3,4,0,1,0,7.44,...,1,0,0,0,12th Pass,Business,Private Company,NaN,NaN,State Assembly Election (AE)

In [65]:
table2

,State_Name,Assembly_No,Constituency_No,Year,month,DelimID,Poll_No,Position,educdum,Margin_Percentage,...,No_Terms,Turncoat,Incumbent,Recontest,MyNeta_education,TCPD_Prof_Main,TCPD_Prof_Main_Desc,TCPD_Prof_Second,TCPD_Prof_Second_Desc,Election_Type
0,Uttar_Pradesh,16,1,2012,3,4,0,2,1,10.13,...,0,0,0,0,Post Graduate,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
1,Uttar_Pradesh,16,3,2012,3,4,0,2,1,16.59,...,0,0,0,0,Graduate,Business,NaN,NaN,NaN,State Assembly Election (AE)
2,Uttar_Pradesh,16,4,2012,3,4,0,2,1,10.07,...,0,0,0,0,Graduate,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
3,Uttar_Pradesh,16,6,2012,3,4,0,2,1,1.62,...,0,0,0,0,Post Graduate,Business,Distributors,NaN,NaN,State Assembly Election (AE)
4,Uttar_Pradesh,16,7,2012,3,4,0,2,1,8.74,...,0,0,0,0,Graduate,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,Uttar_Pradesh,16,397,2012,3,4,0,2,1,24.89,...,0,0,0,0,Graduate Professional,Other,NaN,NaN,NaN,State Assembly Election (AE)
259,Uttar_Pradesh,16,398,2012,3,4,0,2,1,5.94,...,0,0,0,0,Post Graduate,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
260,Uttar_Pradesh,16,400,2012,3,4,0,2,1,28.67,...,2,0,1,1,Post Graduate,Business,Rent,NaN,NaN,State Assembly Election (AE)
261,Uttar_Pradesh,16,401,2012,3,4,0,2,1,13.13,...,0,0,0,0,Graduate,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
262,Uttar_Pradesh,16,402,2012,3,4,0,2,1,2.21,...,0,0,0,0,Graduate,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)

In [66]:
merged = pd.merge(table1, table2, on='Constituency_No')

In [67]:
merged

,State_Name_x,Assembly_No_x,Constituency_No,Year_x,month_x,DelimID_x,Poll_No_x,Position_x,educdum_x,Margin_Percentage_x,...,No_Terms_y,Turncoat_y,Incumbent_y,Recontest_y,MyNeta_education_y,TCPD_Prof_Main_y,TCPD_Prof_Main_Desc_y,TCPD_Prof_Second_y,TCPD_Prof_Second_Desc_y,Election_Type_y
0,Uttar_Pradesh,16,4,2012,3,4,0,1,0,8.39,...,0,0,0,0,Graduate,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
1,Uttar_Pradesh,16,12,2012,3,4,0,1,0,7.37,...,0,0,0,0,Post Graduate,Salaried Work or Employed,Insurance Agent,NaN,NaN,State Assembly Election (AE)
2,Uttar_Pradesh,16,15,2012,3,4,0,1,0,3.45,...,0,1,0,1,Post Graduate,Retired or Pension,NaN,Agriculture,NaN,State Assembly Election (AE)
3,Uttar_Pradesh,16,16,2012,3,4,0,1,0,7.55,...,1,0,1,1,Graduate,Politics,Party Worker,NaN,NaN,State Assembly Election (AE)
4,Uttar_Pradesh,16,17,2012,3,4,0,1,0,6.19,...,0,0,0,0,Post Graduate,Business,NaN,Agriculture,NaN,State Assembly Election (AE)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Uttar_Pradesh,16,386,2012,3,4,0,1,0,6.86,...,0,0,0,0,Post Graduate,Liberal Profession or Professional,Doctor,NaN,NaN,State Assembly Election (AE)
70,Uttar_Pradesh,16,392,2012,3,4,0,1,0,7.78,...,1,0,1,1,Graduate,Social Work,NaN,NaN,NaN,State Assembly Election (AE)
71,Uttar_Pradesh,16,395,2012,3,4,0,1,0,5.55,...,0,0,0,0,Graduate Professional,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
72,Uttar_Pradesh,16,397,2012,3,4,0,1,0,4.61,...,0,0,0,0,Graduate Professional,Other,NaN,NaN,NaN,State Assembly Election (AE)
73,Uttar_Pradesh,16,400,2012,3,4,0,1,0,7.44,...,2,0,1,1,Post Graduate,Business,Rent,NaN,NaN,State Assembly Election (AE)

In [68]:
# filter merged DataFrame based on S values
result = merged[(merged['educdum_x'] == 0) & (merged['educdum_y'] == 1)]

In [69]:
result

,State_Name_x,Assembly_No_x,Constituency_No,Year_x,month_x,DelimID_x,Poll_No_x,Position_x,educdum_x,Margin_Percentage_x,...,No_Terms_y,Turncoat_y,Incumbent_y,Recontest_y,MyNeta_education_y,TCPD_Prof_Main_y,TCPD_Prof_Main_Desc_y,TCPD_Prof_Second_y,TCPD_Prof_Second_Desc_y,Election_Type_y
0,Uttar_Pradesh,16,4,2012,3,4,0,1,0,8.39,...,0,0,0,0,Graduate,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
1,Uttar_Pradesh,16,12,2012,3,4,0,1,0,7.37,...,0,0,0,0,Post Graduate,Salaried Work or Employed,Insurance Agent,NaN,NaN,State Assembly Election (AE)
2,Uttar_Pradesh,16,15,2012,3,4,0,1,0,3.45,...,0,1,0,1,Post Graduate,Retired or Pension,NaN,Agriculture,NaN,State Assembly Election (AE)
3,Uttar_Pradesh,16,16,2012,3,4,0,1,0,7.55,...,1,0,1,1,Graduate,Politics,Party Worker,NaN,NaN,State Assembly Election (AE)
4,Uttar_Pradesh,16,17,2012,3,4,0,1,0,6.19,...,0,0,0,0,Post Graduate,Business,NaN,Agriculture,NaN,State Assembly Election (AE)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Uttar_Pradesh,16,386,2012,3,4,0,1,0,6.86,...,0,0,0,0,Post Graduate,Liberal Profession or Professional,Doctor,NaN,NaN,State Assembly Election (AE)
70,Uttar_Pradesh,16,392,2012,3,4,0,1,0,7.78,...,1,0,1,1,Graduate,Social Work,NaN,NaN,NaN,State Assembly Election (AE)
71,Uttar_Pradesh,16,395,2012,3,4,0,1,0,5.55,...,0,0,0,0,Graduate Professional,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
72,Uttar_Pradesh,16,397,2012,3,4,0,1,0,4.61,...,0,0,0,0,Graduate Professional,Other,NaN,NaN,NaN,State Assembly Election (AE)
73,Uttar_Pradesh,16,400,2012,3,4,0,1,0,7.44,...,2,0,1,1,Post Graduate,Business,Rent,NaN,NaN,State Assembly Election (AE)

In [70]:
# select columns from table1
subset = result[[col for col in result.columns if col.endswith('_x')]]

In [71]:
subset

,State_Name_x,Assembly_No_x,Year_x,month_x,DelimID_x,Poll_No_x,Position_x,educdum_x,Margin_Percentage_x,Candidate_x,...,No_Terms_x,Turncoat_x,Incumbent_x,Recontest_x,MyNeta_education_x,TCPD_Prof_Main_x,TCPD_Prof_Main_Desc_x,TCPD_Prof_Second_x,TCPD_Prof_Second_Desc_x,Election_Type_x
0,Uttar_Pradesh,16,2012,3,4,0,1,0,8.39,JAGPAL,...,1,0,0,0,12th Pass,Politics,Party Worker,Agriculture,NaN,State Assembly Election (AE)
1,Uttar_Pradesh,16,2012,3,4,0,1,0,7.37,NOOR SALEEM RANA,...,1,0,0,0,12th Pass,Business,NaN,NaN,NaN,State Assembly Election (AE)
2,Uttar_Pradesh,16,2012,3,4,0,1,0,3.45,KARTAR SINGH BHADANA,...,1,0,0,0,8th Pass,Business,NaN,Agriculture,NaN,State Assembly Election (AE)
3,Uttar_Pradesh,16,2012,3,4,0,1,0,7.55,JAMIL AHMAD QASMI,...,1,0,0,0,Literate,Education,School Teacher,NaN,NaN,State Assembly Election (AE)
4,Uttar_Pradesh,16,2012,3,4,0,1,0,6.19,TASLEEM,...,1,0,0,0,Literate,Other,NaN,NaN,NaN,State Assembly Election (AE)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Uttar_Pradesh,16,2012,3,4,0,1,0,6.86,UDAY LAL MAURYA,...,2,0,1,1,10th Pass,Business,Rent,NaN,NaN,State Assembly Election (AE)
70,Uttar_Pradesh,16,2012,3,4,0,1,0,7.78,JAHID BEG,...,1,0,0,0,12th Pass,Salaried Work or Employed,Insurance Agent,NaN,NaN,State Assembly Election (AE)
71,Uttar_Pradesh,16,2012,3,4,0,1,0,5.55,BHAI LAL KOL,...,1,0,0,0,10th Pass,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
72,Uttar_Pradesh,16,2012,3,4,0,1,0,4.61,RAMESH CHAND,...,1,0,0,0,12th Pass,Other,NaN,NaN,NaN,State Assembly Election (AE)
73,Uttar_Pradesh,16,2012,3,4,0,1,0,7.44,RAMESH CHANDRA,...,1,0,0,0,12th Pass,Business,Private Company,NaN,NaN,State Assembly Election (AE)

file_name = 'data.xlsx'
  
# saving the excel
data_frame1.to_excel(file_name,sheet_name="Tamil_Nadu",)

In [72]:

## import dataframe in same excel and write inside the file saved
import openpyxl
from openpyxl.utils.dataframe import dataframe_to_rows

workbook = openpyxl.load_workbook('final_nongradwin2013.xlsx')

# create a new worksheet
new_sheet = workbook.create_sheet('Uttar_Pradesh')

# write data to the new worksheet
new_data = subset

# Write the DataFrame to the new worksheet
rows = dataframe_to_rows(new_data, index=False, header=True)
for r_idx, row in enumerate(rows, 1):
    for c_idx, value in enumerate(row, 1):
        new_sheet.cell(row=r_idx, column=c_idx, value=value)
        
# save the updated workbook
workbook.save('final_nongradwin2013.xlsx')